package asm

import (
	"fmt"
	"os"

	"github.com/laghoule/tiled2map/internal/pkg/tiled"
)

const (
	tileAttribute = "attr"
)

// createTilesRefs generates the ASM tile references file
// TODO: separa create tilesRefs & file creation
func createTilesRefs(filePrefix string, tilesInfo []tiled.TileInfo) error {
	filename := fmt.Sprintf("%s.inc", filePrefix)
	asmFile, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer asmFile.Close()

	fmt.Fprintf(asmFile, "; GENERATED BY tiled2map\n")
	fmt.Fprintf(asmFile, "; DO NOT EDIT\n\n")
	fmt.Fprintf(asmFile, "TILES_PROPS LABEL BYTE\n")

	for idx, tileInfo := range tilesInfo {
		attr := 0.0
		for _, tile := range tileInfo.Tiles {
			for _, prop := range tile.Properties {
				if prop.Name == tileAttribute {
					ok := false
					attr, ok = prop.Value.(float64)
					if !ok {
						return fmt.Errorf("invalid attribute value for tile %d: %v\n", tileInfo.GID, prop.Value)
					}
					break
				}
			}
		}
		fmt.Fprintf(asmFile, "  DB %08bb ; Index: %2d (GID: %3d Source: %s)\n", int(attr), idx, tileInfo.GID, tileInfo.SourceImage)
	}

	return nil
}
